### PR TITLE
Close input files when finished with them.

### PR DESCRIPTION
**Pull request by mickp**
Close input files when finished rather than relying on closing at process exit.

### CODE REVIEW

**Comment by tkmru** [comment]
LGTM 👍

**Comment by mickp** [comment]
Oops. I think my 'fix' broke the merging later on. A friend is using your
functions in a script, and had problems with residual open files. I did
this as a quick fix to get him going. We'll fix it properly and send
another PR. He's also fixing it up for Python 3.

**Comment by tkmru** [comment]
ok, I reverted.

**Comment by mickp** [comment]
Great - sorry about that. Will test for both single and multiple inputs
before submitting next PR.

**Pull request merged**
